<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>VoiceDuck</RootNamespace>
    <AssemblyName>VoiceDuck</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>5</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NAudio.Core">
      <HintPath>..\..\third_party\NAudio\2.3.0\NAudio.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="NAudio.Wasapi">
      <HintPath>..\..\third_party\NAudio\2.3.0\NAudio.Wasapi.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\third_party\VBCABLE\VBCABLE_Driver_Pack45.zip">
      <LogicalName>VoiceDuck.Resources.VBCABLE_Driver_Pack45.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
